## Binomial Model Hedging

In [5]:
import numpy as np
from math import floor
import matplotlib.pyplot as plt

In [6]:
# defining variables
N_periods=5 #number of periods
u=1.1 #the upward movement in stock
d=0.9 #the downward movement in stock
r=0.05 #the interest rate per period
S0=100 #the initial stock price
K=95  #the strike price
S=np.zeros((N_periods+1,N_periods+1))
for n in range(N_periods+1):
    for m in range (n+1):
        S[m,n]=S0*u**(n-m)*d**m
#risk neutral probabilities
qu=((1+r)-d)/(u-d)
qd= 1- qu

# pricing by backward induction
option_price=np.zeros((N_periods+1,N_periods+1)) # matrix for the option price
delta=np.zeros((N_periods+1,N_periods+1)) # matrix for delta of the option (replicating portfolio)

In [7]:
# Computing payoff payoff
for m in range(N_periods+1): #set the last column of the option price matrix equal to the payoff of the option
    option_price[m,N_periods]=max(K-S[m,N_periods],0) # the payoff of a call optionprint(
for n in reversed(range(N_periods)): # go backward in time-to-maturity
    for m in range(n+1):    #go through all stock prices at time-to-maturity n
        option_price_up=option_price[m,n+1] # the value of the option if stock goes up
        option_price_down=option_price[m+1,n+1] #the value of the option if stock goes down
        delta[m,n]=(option_price_up-option_price_down)/(S[m,n]*(u-d)) #compute delta
        option_price[m,n]=(option_price_up*qu+option_price_down*qd)/(1+r) #compute the current option price using risk-neutral pricing formula (the price is equal to expected discounted payoff)

# display the results
print('stock price \n',S)
print('option price \n',option_price)
print('delta of the option \n',delta)
print('the price of the option at time 0 is',option_price[0,0])
print('the Delta at time 0 is',delta[0,0]) 

stock price 
 [[100.    110.    121.    133.1   146.41  161.051]
 [  0.     90.     99.    108.9   119.79  131.769]
 [  0.      0.     81.     89.1    98.01  107.811]
 [  0.      0.      0.     72.9    80.19   88.209]
 [  0.      0.      0.      0.     65.61   72.171]
 [  0.      0.      0.      0.      0.     59.049]]
option price 
 [[ 0.75718622  0.33525447  0.09166127  0.          0.          0.        ]
 [ 0.          2.17441871  1.13308498  0.38497732  0.          0.        ]
 [ 0.          0.          5.73330364  3.60402494  1.61690476  0.        ]
 [ 0.          0.          0.         13.26780045 10.28619048  6.791     ]
 [ 0.          0.          0.          0.         24.86619048 22.829     ]
 [ 0.          0.          0.          0.          0.         35.951     ]]
delta of the option 
 [[-0.09195821 -0.04733744 -0.01590815  0.          0.          0.        ]
 [ 0.         -0.2555677  -0.16257816 -0.07423805  0.          0.        ]
 [ 0.          0.         -0.59652935 -0.